#!/usr/bin/env bash

# This is derived from:
# https://code.ornl.gov/sochat1/mummi-ras/-/blob/mini-mummi/setup/launch_workflow.sh

# assume one node for now. one node == one pod.
# if this scales, we might do with replicas, but not sure that makes sense.
mummi_nnodes=${1:-1}

# This is needed in the wfmanager
# hard coded to match mlserver only running on one node
export MUMMI_MLSERVER_NNODES=1

# The user needs to be mummiusr and not root to get the right queue name
export USER=mummiusr

# This needs to minimally be the number of jobs.. or you get a negative number (and error)
# IMPORTANT - in Kubernetes we don't need to control nodes like this - we can autoscale.
export MUMMI_NNODES={{ if .Spec.WorkflowManager.Nodes }}{{ .Spec.WorkflowManager.Nodes }}{{ else }}6{{ end }}
export NCORES_PER_NODE={{ if .Spec.WorkflowManager.CoresPerNode }}{{ .Spec.WorkflowManager.CoresPerNode }}{{ else }}4{{ end }}

# Since the above is likely used for other purposes, we have a new varible defined
# for what we allow the cluster jobs to scale to. E.g., how man jobs can stack
# up in the Kubernetes queue.
export KUBERNETES_MAX_NODES={{ if .Spec.WorkflowManager.MaxNodes }}{{ .Spec.WorkflowManager.MaxNodes }}{{ else }}${MUMMI_NNODES}{{ end }}

# This adds our custom kubernetesTracker.py to the path
echo "Looking for kubernetesTracker.py"
ls /opt
if [[ ! -f "/opt/kubernetesTracker.py" ]]; then
    echo "/opt/kubernetesTracker.py to submit k8s jobs is missing."
    exit 1
fi
export PYTHONPATH=$PYTHONPATH:/opt

# Use provided container mummi_ras
MUMMI_ROOT={{ if .Spec.Paths.MummiRoot }}{{ .Spec.Paths.MummiRoot }}{{ else }}/opt/clones/mummi-ras{{ end }}
MUMMI_APP={{ if .Spec.Paths.MummiApp }}{{ .Spec.Paths.MummiApp }}{{ else }}/opt/mummi-app{{ end }}
export MUMMI_RESOURCES={{ if .Spec.Paths.MummiResources }}{{ .Spec.Paths.MummiResources }}{{ else }}/opt/clones/mummi_resources{{ end }}
export MUMMI_APP MUMMI_ROOT

echo "(`hostname`: `date`) --> Launching MuMMI workflow ($mummi_nnodes nodes)"
pushd $MUMMI_ROOT/workspace > /dev/null 2>&1

TMP_DIR="/tmp/gen_chk"

# check if wfmanager.chk exists. Maybe we bind one to the container?
if [ ! -f "wfmanager.chk" ]; then
    echo "(`hostname`: `date`) --> [Warning] File wfmanager.chk doesn't exist. Generate a new wfmanager.chk..."
    rm -rf $TMP_DIR
    mkdir $TMP_DIR
    python3 $MUMMI_APP/mummi_ras/scripts/update_wf_chkpt.py create $TMP_DIR
    cat $TMP_DIR/wfmanager_*.chk.yml
    cp $TMP_DIR/wfmanager_*.chk.yml wfmanager.chk
    rm -rf $TMP_DIR
    if [ ! -f "wfmanager.chk" ]; then
      echo "(`hostname`: `date`) --> [Error] Fail to generate wfmanager.chk. Exiting..."
      exit 1
    fi
fi

chk_file_size=`wc -c wfmanager.chk | awk '{print $1}'`
if [ $chk_file_size -lt 400 ]; then
  echo "(`hostname`: `date`) --> Checkpoint file wfmanager.chk is corrupted with size of $chk_file_size"
  chk_file=`ls -tr wfmanager.chk.bak.* |tail -n 1`
  cp $chk_file wfmanager.chk
  cp $chk_file wfmanager_test.chk
  echo "(`hostname`: `date`) --> Replace wfmanager.chk with backup $chk_file"
else
  echo "(`hostname`: `date`) --> Checkpoint file wfmanager.chk is fine size of $chk_file_size"
fi

sh $MUMMI_APP/setup/utils/backup_wspace.sh

# This normally was a flux submit, but we can just run it natively here.
echo "(`hostname`: `date`) --> Launching workflow"

# Rabbit mq connection stuff
# This gets the rabbitmq script if we need it (I didn't use it yet)
# We could change to https and use port 15671 here instead
# curl http://rabbitmq.mini-mummi.default.svc.cluster.local:15672/cli/rabbitmqadmin -o /usr/local/bin/rabbitmqadmin  
curl http://{{ .Mummi.RabbitHost }}:15672/cli/rabbitmqadmin -o /usr/local/bin/rabbitmqadmin
chmod +x /usr/local/bin/rabbitmqadmin  

# Create dummy credentials
mkdir -p $MUMMI_ROOT/mlserver

# Tidbits from the setup_env.sh script

# ------------------------------------------------------------------------------
# check the paths. these should be pointing to the virtual env
echo "mummi_core:" `python -c "import mummi_core; print (mummi_core.__path__)"`
echo "mummi_ras:"  `python -c "import mummi_ras; print (mummi_ras.__path__)"`

# Copy credentials generated by operator, mapped to file from secret
cp /cert_rabbitmq/rabbitmq-credentials.json $MUMMI_ROOT/mlserver/rabbitmq-credentials.json

# TODO look here:
# https://code.ornl.gov/admirral/mummi-ras/-/blob/develop/setup/launch_workflow.sh?ref_type=heads#L69-89
# and decide if we want to use autobind as well (not sure why the wfmanager would need it?)
cmd="python3 $MUMMI_APP/mummi_ras/scripts/run_wfmanager.py"
echo $cmd
$cmd
