apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: registry
spec:
  serviceName: mini-mummi
  replicas: 1
  selector:
    matchLabels:
      app: mini-mummi
  template:
    metadata:
      labels:
        app: mini-mummi
    spec:
      subdomain: mini-mummi
      hostname: registry
      containers:
      - name: registry
        image: ghcr.io/oras-project/registry:latest
        # ports:
        #- containerPort: 80
        #  name: web
        # TODO we can ad REGISTRY_HTTP_SECRET as a secret envar
        #env:
        #  - name: REGISTRY_HTTP_SECRET
        #    value: somevaluefromsecret
