apiVersion: apps/v1
kind: Deployment
metadata:
  name: wfmanager
spec:
  selector:
    matchLabels:
      app: mini-mummi
  replicas: 1
  template:
    metadata:
      labels:
        # Matches the headless service
        app: mini-mummi
    spec:
      subdomain: mini-mummi
      hostname: wfmanager
      containers:
      - name: manager
        image: 633731392008.dkr.ecr.us-east-1.amazonaws.com/mini-mummi:manager
        command: ["sleep", "infinity"]
        #command: ["/bin/bash"]
        #args: ["/entrypoint.sh", "kube"]
        # This ensures we use the kind loaded image
        # remove if this isn't the case
        imagePullPolicy: Never
