# see https://prefix.dev/docs/pixi/configuration
[project]
name = "mummi-ml-ucg"
version = "0.1.0"
authors = ["Vanessa Sochat <sochat1@llnl.gov>"]
channels = ["pytorch", "conda-forge"]
platforms = ["linux-64"]
description = "The ml-ucg component for a MuMMI container build"
license = "MIT"

[build-dependencies]
pkg-config = "~=0.29.2"

# cmake is needed for pip install horovod
[dependencies]
cmake = "3.24*"
lammps = "2023.8.2.*"
python = "3.11.6.*"
h5py = "3.9.0.*"
pandas = "2.1.1.*"
scikit-learn = "1.3.1.*"
xgboost = "1.7.6.*"
keras = "2.13.1.*"
keras-applications = "1.0.8.*"
keras-preprocessing = "1.1.2.*"
gxx = "11.4.0.*"
gromacs = "2023.2.*"
gcc = "11.4.0.*"
git = "2.42.0.*"
pip = "23.2.1.*"
pytorch = "2.0.0.*"
pytorch_geometric = "2.1.0.post1.*"
torchvision = "0.15.2.*"
pytorch_scatter = "2.1.2.*"
torchtext = "0.15.2.*"
mpi4py = "3.1.4.*"
pillow = "10.0.1.*"
cxx-compiler = "1.5.2.*"
nccl = "2.19.3.1.*"
nvcc_linux-64 = "10.2.*"
cudnn = "8.8.0.121.*"
mdanalysis = "2.6.1.*"
faiss = "1.7.4.*"
pot = "0.9.1.*"

[pypi-dependencies]
watchdog = "*"
