//go:build !ignore_autogenerated

/*
Copyright 2024.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by controller-gen. DO NOT EDIT.

package v1alpha1

import (
	runtime "k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *JobConfig) DeepCopyInto(out *JobConfig) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new JobConfig.
func (in *JobConfig) DeepCopy() *JobConfig {
	if in == nil {
		return nil
	}
	out := new(JobConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Logging) DeepCopyInto(out *Logging) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Logging.
func (in *Logging) DeepCopy() *Logging {
	if in == nil {
		return nil
	}
	out := new(Logging)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MLServer) DeepCopyInto(out *MLServer) {
	*out = *in
	out.Config = in.Config
	out.RabbitMQ = in.RabbitMQ
	out.Encoder = in.Encoder
	out.Sampler = in.Sampler
	out.Validator = in.Validator
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MLServer.
func (in *MLServer) DeepCopy() *MLServer {
	if in == nil {
		return nil
	}
	out := new(MLServer)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MLServerConfig) DeepCopyInto(out *MLServerConfig) {
	*out = *in
	out.Logging = in.Logging
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MLServerConfig.
func (in *MLServerConfig) DeepCopy() *MLServerConfig {
	if in == nil {
		return nil
	}
	out := new(MLServerConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MLServerEncoder) DeepCopyInto(out *MLServerEncoder) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MLServerEncoder.
func (in *MLServerEncoder) DeepCopy() *MLServerEncoder {
	if in == nil {
		return nil
	}
	out := new(MLServerEncoder)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MLServerSampler) DeepCopyInto(out *MLServerSampler) {
	*out = *in
	out.Feedback = in.Feedback
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MLServerSampler.
func (in *MLServerSampler) DeepCopy() *MLServerSampler {
	if in == nil {
		return nil
	}
	out := new(MLServerSampler)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MLServerValidator) DeepCopyInto(out *MLServerValidator) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MLServerValidator.
func (in *MLServerValidator) DeepCopy() *MLServerValidator {
	if in == nil {
		return nil
	}
	out := new(MLServerValidator)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MiniMummi) DeepCopyInto(out *MiniMummi) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	out.Spec = in.Spec
	out.Status = in.Status
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MiniMummi.
func (in *MiniMummi) DeepCopy() *MiniMummi {
	if in == nil {
		return nil
	}
	out := new(MiniMummi)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *MiniMummi) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MiniMummiList) DeepCopyInto(out *MiniMummiList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]MiniMummi, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MiniMummiList.
func (in *MiniMummiList) DeepCopy() *MiniMummiList {
	if in == nil {
		return nil
	}
	out := new(MiniMummiList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *MiniMummiList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MiniMummiSpec) DeepCopyInto(out *MiniMummiSpec) {
	*out = *in
	out.Registry = in.Registry
	out.Paths = in.Paths
	out.MLServer = in.MLServer
	out.RabbitMQ = in.RabbitMQ
	out.WorkflowManager = in.WorkflowManager
	out.Jobs = in.Jobs
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MiniMummiSpec.
func (in *MiniMummiSpec) DeepCopy() *MiniMummiSpec {
	if in == nil {
		return nil
	}
	out := new(MiniMummiSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MiniMummiStatus) DeepCopyInto(out *MiniMummiStatus) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MiniMummiStatus.
func (in *MiniMummiStatus) DeepCopy() *MiniMummiStatus {
	if in == nil {
		return nil
	}
	out := new(MiniMummiStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MummiJob) DeepCopyInto(out *MummiJob) {
	*out = *in
	out.Config = in.Config
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MummiJob.
func (in *MummiJob) DeepCopy() *MummiJob {
	if in == nil {
		return nil
	}
	out := new(MummiJob)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MummiJobs) DeepCopyInto(out *MummiJobs) {
	*out = *in
	out.CgAnalysis = in.CgAnalysis
	out.CreateSim = in.CreateSim
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MummiJobs.
func (in *MummiJobs) DeepCopy() *MummiJobs {
	if in == nil {
		return nil
	}
	out := new(MummiJobs)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MummiPaths) DeepCopyInto(out *MummiPaths) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MummiPaths.
func (in *MummiPaths) DeepCopy() *MummiPaths {
	if in == nil {
		return nil
	}
	out := new(MummiPaths)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *OrasConfig) DeepCopyInto(out *OrasConfig) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new OrasConfig.
func (in *OrasConfig) DeepCopy() *OrasConfig {
	if in == nil {
		return nil
	}
	out := new(OrasConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RabbitMQ) DeepCopyInto(out *RabbitMQ) {
	*out = *in
	out.Broker = in.Broker
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RabbitMQ.
func (in *RabbitMQ) DeepCopy() *RabbitMQ {
	if in == nil {
		return nil
	}
	out := new(RabbitMQ)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RabbitMQBroker) DeepCopyInto(out *RabbitMQBroker) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RabbitMQBroker.
func (in *RabbitMQBroker) DeepCopy() *RabbitMQBroker {
	if in == nil {
		return nil
	}
	out := new(RabbitMQBroker)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SamplerFeedback) DeepCopyInto(out *SamplerFeedback) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SamplerFeedback.
func (in *SamplerFeedback) DeepCopy() *SamplerFeedback {
	if in == nil {
		return nil
	}
	out := new(SamplerFeedback)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *WorkflowManager) DeepCopyInto(out *WorkflowManager) {
	*out = *in
	out.Logging = in.Logging
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new WorkflowManager.
func (in *WorkflowManager) DeepCopy() *WorkflowManager {
	if in == nil {
		return nil
	}
	out := new(WorkflowManager)
	in.DeepCopyInto(out)
	return out
}
