default_vhost = /{{ if .Spec.RabbitMQ.Vhost }}{{ .Spec.RabbitMQ.Vhost }}{{ else }}dinosaur_vhost{{ end }}
default_user = {{ if .Spec.RabbitMQ.User }}{{ .Spec.RabbitMQ.User }}{{ else }}dinosaur{{ end }}
default_pass = {{ if .Spec.RabbitMQ.Pass }}{{ .Spec.RabbitMQ.Pass }}{{ else }}dinosaur{{ end }}

listeners.ssl.default = 5671
consumer_timeout = {{ if .Spec.RabbitMQ.ConsumerTimeout }}{{ .Spec.RabbitMQ.ConsumerTimeout }}{{ else }}10800000{{ end }}

ssl_options.cacertfile = /cert_rabbitmq/ca_certificate.pem
ssl_options.certfile   = /cert_rabbitmq/server_rabbitmq_certificate.pem
ssl_options.keyfile    = /cert_rabbitmq/server_rabbitmq_key.pem
ssl_options.verify     = verify_none
ssl_options.fail_if_no_peer_cert = false
